# Generated by Django 5.2 on 2025-04-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_pdf', models.FileField(upload_to='pdfs/')),
                ('ocr_pdf', models.FileField(blank=True, null=True, upload_to='ocr_pdfs/')),
                ('status', models.CharField(choices=[('uploaded', 'Subido'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('ocr_text', models.FileField(blank=True, null=True, upload_to='ocr_text/')),
            ],
        ),
    ]
